# Generated by Django 5.1.5 on 2025-01-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
