# Generated by Django 5.1.5 on 2025-01-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
    ]
