# Generated by Django 5.1.5 on 2025-01-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
