# Generated by Django 5.1.5 on 2025-02-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ttitle',
            new_name='title',
        ),
    ]
